# Header Menu
menu:
  Home: /
  Amazon Web Services: /aws/
  DevOps: /devops/
  Blog: /archives/ # can set archive-dir in root config to custom value
  Contact: /contact/
   
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname: 
google_analytics:
swiftype_install_key: 

# Social
social:
  github: https://github.com/MoiCoquille
  twitter: https://twitter.com/indalitcloud
#  facebook: https://www.facebook.com/ptsteadman
#  rss: atom.xml
  linkedin: https://www.linkedin.com/company/indalit-cloud-consulting/
#  stackoverflow: http://stackoverflow.com/users/2480493/patrick-steadman

# Miscellaneous
color_scheme: red   # options: blue, gray, green, orange, red, turquoise
favicon: /images/favicon.ico # path from root of hexo site
#  twitter_widget_id: "678830341331820544" # as a string, from https://twitter.com/settings/widgets
twitter_widget_id: "940245897694367744"
#  twitter_username: computerlab_ # twitter username without the @
twitter_username: indalitcloud # twitter username without the @
default_author: Veronique

about: Indalit Cloud Consulting is a company specialized in AWS, Amazon Web Services. <br><br> Indalit is composed of AWS Certified Solutions Architects and devops engineers working world wide to provide high quality solutions.
phone: +34 963 684 585
email: info@indalit.com
address_1: Calle Reina Violante 5
address_2: 46015 Valencia 
address_3: Spain
#  skype: ptsteadman
lat: 40.715911 
long: -73.962147
